<div id="auth">
    <div id="auth_title">
        <img src="img/gear.png" alt="engrenage" id="gear">
        <p class="centred">&bull; Espace d'administration &bull;</p>
    </div>
    <div id="auth_logo" class="centred">
        <h1 class="title">Yoann Buchet</h1>
        <h2 class="subtitle">Multiservices</h2>
    </div>
    <form id="auth_form" action='index.php' method='post'>
        <input name='login' type='text' placeholder='Identifiant' required/>
        <input id="last" name='password' type='password' placeholder='Mot de passe' required/>
        <input id="button_submit" type='submit' value='Connexion'/>
    </form>
</div>